version: '3'

services:
  web:
    build:
      context: .
      dockerfile: dockerfile
    volumes:
      - ./srv/jupyterhub:/srv/jupyterhub
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
